services:
  backend:
    build:
      context: .
    env_file:
      - .env
    ports:
      - "5000:3000"
    volumes:
      - ./data:/app/data
    networks:
      - sinistra_network

  dashboard:
    build:
      context: ../dashboard
    ports:
      - "${DASHBOARD_PORT:-8501}:8501"
    depends_on:
      - backend
    networks:
      - sinistra_network

  bot:
    profiles: [discord]
    build:
      context: ../bot
    command: ["/bin/bash", "/app/entrypoint.sh"]
    env_file:
      - ../bot/.env
    environment:
      - API_BASE=http://backend:3000/api/
    volumes:
      - ../bot:/app
    working_dir: /app
    depends_on:
      - backend
    networks:
      - sinistra_network

networks:
  sinistra_network:
    driver: bridge

